/**********************************************************************************************************************
 * \file Driver_ASP.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include <ASCLIN3_USB_UART.h>
#include <Driver_serialPlotter.h>

#include "_Utilities/Ifx_Assert.h"

#include <string.h>
#include <stdio.h>
#include <stdarg.h>

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static struct {
        char format_string[VAR_MONITORING_STRING_SIZE + 1];
        void *p_var;
        uint8 var_size;
}var_list[10];
static uint8 var_list_cnt = 0;


/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void SP_install_var(char *name, char *format_specifier, void* p_var, uint8 var_size) {
    uint32 name_length = strlen(name);
    uint32 format_specifier_length = strlen(format_specifier);
    if(name_length + format_specifier_length > VAR_MONITORING_STRING_SIZE) return;

    var_list[var_list_cnt].format_string[0] = '\0';
    strncat(var_list[var_list_cnt].format_string, name, strlen(name));
    strncat(var_list[var_list_cnt].format_string, ":", strlen(":"));
    strncat(var_list[var_list_cnt].format_string, format_specifier, strlen(format_specifier));

    var_list[var_list_cnt].p_var = p_var;

    var_list[var_list_cnt].var_size = var_size;
    var_list_cnt++;
}

void plotting_variable() {
    for(int i = 0 ; i < var_list_cnt; i++) {
        USB_printf(var_list[i].format_string, var_list[i].p_var);
        if(i == var_list_cnt)
            USB_printf("\n");
        else
            USB_printf(", ");
    }
}



void USB_printf(pchar format,...)
{
    char      message[USB_UART_MAX_PRINT_SIZE + 1];
    Ifx_SizeT count;
    va_list   args;
    va_start(args, format);
    vsprintf((char *)message, format, args);
    va_end(args);
    count = (Ifx_SizeT)strlen(message);
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, count < STDIF_DPIPE_MAX_PRINT_SIZE);
    USB_print_string(message, USB_UART_MAX_PRINT_SIZE);
    //return

}

void USB_print_string(char *str, uint32 max_len) {
    uint32 count = 0;

    char ch = *str;
    while(ch != 0 && count < max_len) {
        if(ch == '\n') {
            asclin3_uart_tx('\r');
            asclin3_uart_tx('\n');
        } else {
            asclin3_uart_tx(ch);
        }
        str++;
        max_len++;
        ch = *str;
    }
}


/*********************************************************************************************************************/
