/**********************************************************************************************************************
 * \file Driver_encoder.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include <Device_driver/Driver_encoder.h>
#include "IfxCpu_Irq.h"


/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
sint32 encoder_data = 0;  // 48 per rotate

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

IFX_INTERRUPT(ENCODER_CHA_ISR, 0, ISR_PRIORITY_ENCODER_CHA);
void ENCODER_CHA_ISR(void){
    if(IfxPort_getPinState(ENCODER_CHA)) { // rising edge triggered
        if(IfxPort_getPinState(ENCODER_CHB)) {
            encoder_data--; // 2 of figure (-)
        } else {
            encoder_data++; // 1 of figure (+)
        }
    } else { // falling edge triggered
        if(IfxPort_getPinState(ENCODER_CHB)) {
            encoder_data++; // 3 of figure (+)
        } else {
            encoder_data--; // 4 of figure (-)
        }
    }
}

IFX_INTERRUPT(ENCODER_CHB_ISR, 0, ISR_PRIORITY_ENCODER_CHB);
void ENCODER_CHB_ISR(void){
    if(IfxPort_getPinState(ENCODER_CHA)) { // rising edge triggered
        if(IfxPort_getPinState(ENCODER_CHB)) {
            encoder_data++; // 5 of figure(+)
        } else {
            encoder_data--; // 8 of figure(-)
        }
    } else { // falling edge triggered
        if(IfxPort_getPinState(ENCODER_CHB)) {
            encoder_data--; // 6 of figure(-)
        } else {
            encoder_data++; // 7 of figure(+)
        }
    }
}


void encoder_init(void){
    //ERU
    //SCU : system Control Unit
    SCU_EICR1.U &= ~(0x7 << EXIS0_IDX);
    SCU_EICR1.U |= 0x1 << EXIS0_IDX;

    SCU_EICR1.U |= 1 << FEN0_IDX;
    SCU_EICR1.U |= 1 << REN0_IDX;
    SCU_EICR1.U |= 1 << EIEN0_IDX;

    SCU_EICR1.U &= ~(0x7 << INP0_IDX);

    SCU_IGCR0.U &= ~(0x3 << IGP0_IDX);
    SCU_IGCR0.U |= 0x1 << IGP0_IDX;

    //SRC : Service Request Control
    SRC_SCU_SCU_ERU0.U &= ~0xFF;
    SRC_SCU_SCU_ERU0.U |= ISR_PRIORITY_ENCODER_CHB;

    SRC_SCU_SCU_ERU0.U |= 1 << SRE_IDX;
    SRC_SCU_SCU_ERU0.U &= ~(0x3 << TOS_IDX);

    //============================================//

    SCU_EICR1.U &= ~(0x7 << EXIS1_IDX);
    SCU_EICR1.U |= 0x2 << EXIS1_IDX;

    SCU_EICR1.U |= 1 << FEN1_IDX;
    SCU_EICR1.U |= 1 << REN1_IDX;
    SCU_EICR1.U |= 1 << EIEN1_IDX;

    SCU_EICR1.U &= ~(0x7 << INP1_IDX);
    SCU_EICR1.U |= 0x1 << INP1_IDX;

    SCU_IGCR0.U &= ~(0x3 << IGP1_IDX);
    SCU_IGCR0.U |= 0x1 << IGP1_IDX;

    //SRC : Service Request Control
    SRC_SCU_SCU_ERU1.U &= ~0xFF;
    SRC_SCU_SCU_ERU1.U |= ISR_PRIORITY_ENCODER_CHA;

    SRC_SCU_SCU_ERU1.U |= 1 << SRE_IDX;
    SRC_SCU_SCU_ERU1.U &= ~(0x3 << TOS_IDX);
}


sint32 encoder_get_rawdata() { // 48/rotate
    return encoder_data;
}

sint32 encoder_get_deci_degrees() { // 48/rotate -> 3600/rotate
    return encoder_data * 75;
}

float32 encoder_get_degrees() { // 48/rotate -> 360'/rotate
    return encoder_data * 7.5;
}

float32 encoder_get_radians() { // 48/rotate -> 2*PI/rotate
    return encoder_data * PI / 24; // encoder_data * 7.5 * 2 * PI / 360;
}


/*********************************************************************************************************************/
